name: Deploy to Firebase Hosting
on:
  push:
    branches:
      - "master"
jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: ./client
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "15"
      - run: yarn install
      - run: yarn build
      - run: yarn export
      - uses: actions/upload-artifact@v2
        with:
          working-directory: ./client/out
          name: out
          path: out
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          working-directory: ./client/out
          name: out
          path: out
      - uses: w9jds/firebase-action@master
        with:
          working-directory: ./client/out
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{secrets.FIREBASE_TOKEN}}